### ISSUE TITLE
Does not work with Laravel 5.2

### ISSUE THREAD

**Issue by deviloflaplace** [comocode/laravel-ab#11]
I've tried this on Laravel v5.2 and Blade directives are not detected. Upon looking at source code I found that Laravel changed how directives are extended between two versions.

Do you have any plans to update this code base?

**Comment by 82rules** [comment]
Yes I plan on keeping this package up to date, thanks for bringing this to attention. 
I won't be working on it directly in the next few days so if you happen to find a solution feel free to PR it otherwise I'll take a look by weeks end.

**Comment by 82rules** [comment]
@deviloflaplace I tested against 5.2 and 5.2.31 and integration worked normally,do you have a specific error or steps to replicate I can look at?
