### ISSUE TITLE
The view throws an exception if laravel_session is expired.

### ISSUE THREAD

**Issue by maxmoore** [comocode/laravel-ab#5]
Great package I love it. One issue I found.

When laravel_session is expired there's an exception thrown in the view.

**ErrorException in Connection.php line 680: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'instance' cannot be null (SQL: insert into `ab_instance` (`instance`, `identifier`, `updated_at`, `created_at`) values (, 127.0.0.1, 2016-06-30 15:54:09, 2016-06-30 15:54:09)) (View: C:\xampp\htdocs\laravel\views\abtesting\home.blade.php)**

**Comment by 82rules** [comment]
sorry took a while to see the issue will make the update shortly along with others, thanks for the kudos!

**Comment by 82rules** [comment]
should be handled now by the latest dev-master update
