### ISSUE TITLE
New instance created each time

### ISSUE THREAD

**Issue by DODMax** [comocode/laravel-ab#6]
Hey, great package.

Somehow duplicated instances are created on each visit for me (one new row in ab_instance each visit with the same instance value) therefore no tracking really happens.

This commit fixed it for me: https://github.com/darekwalega/laravel-ab/commit/40f4a14264ff792697caae96781f595422e01be2

**Comment by DODMax** [comment]
I guess the proper fix would be to store NULL instead of serializing null while saving Instance. This should fix it: https://github.com/comocode/laravel-ab/pull/7

**Comment by 82rules** [comment]
Took me a while to see the issue and fix, appreciate the contribution!
